# Generated by Django 4.1.2 on 2022-11-28 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_payment'),
        ('userApp', '0002_alter_mycart_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('details', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.userinfo')),
            ],
            options={
                'db_table': 'OrderMaster',
            },
        ),
    ]
